services:
  visualizer:
    image: ghcr.io/autowarefoundation/autoware-tools:visualizer-20251009
    volumes:
      - ./etc/simulation:/autoware/scenario-sim
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=26
      - DISPLAY=${DISPLAY}
      - REMOTE_DISPLAY=true
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - RVIZ_CONFIG=/autoware/scenario-sim/rviz/autoware.rviz
    ports:
      - 6080:6080 
